### ISSUE TITLE
Bot API 4.6

### ISSUE THREAD

**Issue by HRankit** [php-telegram-bot/core#1049]
### 🎉 Feature Request
https://core.telegram.org/bots/api#january-23-2020

#### Summary
Could you please integrate Polls 2.0
I want to be able to save the quiz poll which was just released. 

It would require a new Database Table which I think I wont be able to do as I couldn't understand how the update gets saved to the database.
Any help towards this will be much appreciated.

**Comment by noplanman** [comment]
Thanks for opening @HRankit, I'll add the checklist of what needs to be implemented here:

**Supported Polls 2.0.**

- [ ] Add the `KeyboardButtonPollType` entity and the field `request_poll` to the `KeyboardButton` entity.
- [ ] Add updates about changes of user answers in non-anonymous polls, represented by the `PollAnswer` entity and the field `poll_answer` in the `Update` entity.
- [ ] Add the fields `total_voter_count`, `is_anonymous`, `type`, `allows_multiple_answers`, `correct_option_id` to the `Poll` entity.
- [ ] Add more information about the bot in response to the `getMe` request: added the fields `can_join_groups`, `can_read_all_group_messages` and `supports_inline_queries` to the `User` entity.
- [ ] Add the optional field `language` to the `MessageEntity` entity.

**Comment by noplanman** [comment]
I've coded the main bulk of the Bot API 4.6, but some things aren't so clear on how to proceed regarding the polls and how they are saved in the DB.

With the native polls, each vote sent the `Poll` object, which was then saved in the database.
Using the Polls 2.0, an anonymous poll vote only sends the `PollAnswer` but not the `Poll` itself, so there is a lack of that data.
A solution would be to save every anonymous poll sent via `sendPoll` directly in the DB as it gets sent out. Would need to check the implications on this.

Also, there will be a new table in the database called `poll_answers` that has all answers to anonymous polls saved.

@php-telegram-bot/developers 
Any thoughts on this?

**Comment by HRankit** [comment]
@noplanman That is exactly what I did. My bot sends polls, as soon as the sendPoll is success, I save it to the DB. When someone answers a quiz mode poll which was created by bot, it saves the poll_answer to the db, else just saves the response of the poll to messages.
About anonymous poll, we can give the user an option to save anonymous polls or not and whether to save it database or not. 
That's what I think would be useful to everyone.

**Comment by noplanman** [comment]
Right, that's what I had in mind too, thanks for your comment.

I don't really like the prospect of coupling the DB more into the library though :confused: 
Especially as it's an idea to extract all DB features to a separate component, to make the core library lighter.

Will see how to implement this nicely, so that it works for all cases :+1:

**Comment by noplanman** [comment]
To keep the foreign key constraints working, it looks like it will need to be added directly to the `Request` class, so that every poll gets saved to the DB, regardless of anonymous or not. That way, when poll answers come to the bot, there is a poll to reference it with.

We'll deal with the decoupling of the DB things when the time comes...

**Comment by noplanman** [comment]
@HRankit I'd appreciate a look into the PR I just made for Bot API 4.6 :pray: 

#1066
