### ISSUE TITLE
How to pass some data to executeCommand() function ?

### ISSUE THREAD

**Issue by kur1977** [php-telegram-bot/core#1061]
Hi.
I need do pass some data through 2-3 steps of chat.

I read about conversation, but I  can't set-up $telegram->enableMySql because of my sql server does not support utf8mb4_unicode_520_ci (((

Is there any other way to send some data or array or variable to executeCommand() ?

**Comment by noplanman** [comment]
Does the data need to be saved for future use or is it just for executing some code in the moment?
For future storage, a database is your best bet.

For passing data around in the moment, you could try to extract any shared functionality that different commands need and use that instead of passing from one command to the next.

If that's not possible for whatever reason, you could also create a helper "storage" class with static variables to save the values, for example.

What's your use case exactly?

**Comment by kur1977** [comment]
@noplanman 
I have an inline button with callback   ['text' => 'REPLY', 'callback_data' => '**updateorder:123** ']
In the callback method I receive the data   **updateorder:123**  where **updateorder** - the command to execute, and the **123** - is the order_id in my site database. Than I need to receive an **answer** from user. Than I need to udate the **comment** column to user **answer** in the order table with the order_id **123**

**Comment by kur1977** [comment]
I edited structure.sql file before import
changed all utf8mb4_unicode_520_ci to utf8mb4_unicode_ci
Than succesfully imported the file ))

Now I can enable mysql in the hook.php and the conversation works fine.

**Comment by jacklul** [comment]
Just gonna drop in that you might be designing your bot in unsafe way since callback data can be manipulated on the client side and you might run into security issues.

**Comment by kur1977** [comment]
@jacklul 
First of all I authenticate all bot users with telephone number. If the telephone number is exists on the site database - than the user can access other bot functionality. The site users is all from my command. They will not manipulate data ))

**Comment by noplanman** [comment]
@kur1977 Have you managed to solve this for yourself? Can I close off here?

**Comment by kur1977** [comment]
> @kur1977 Have you managed to solve this for yourself? Can I close off here?

Yes. Thanks.
