### ISSUE TITLE
Keyboard configurator

### ISSUE THREAD

**Issue by asafov** [php-telegram-bot/core#1097]
#### Summary
I think about something like keyboard configurator with codegenerator of commands.
At the end of script execution user will receive zip-file with pre-generated commands.

That do you think, guys? How about do this tool together?

**Comment by noplanman** [comment]
What kind of commands do you have in mind?
To make a more complex command, this generator would need to be pretty complex.

You're of course always welcome to start developing something. It could be an addon to the core project :+1:

**Comment by asafov** [comment]
I mean something like simple visual editor for commands.
For example user click "Add command" and write "/start".
Next he will be choise needed action (Call external script, send response, etc).
I will think about conception.

**Comment by noplanman** [comment]
So the command itself still needs to be specifically written.

This could be an idea for a CLI application, to help generate commands from a template or something.

>  I will think about conception.

Ok! :+1:

**Comment by asafov** [comment]
Yes, i mean something like CLI with actions and algo for generate commands codebase.

**Comment by Hitmare** [comment]
Well you could 'easy' generate the code for the Keyboard array that the user can copy into his command

since there is a limited function that the keyboard can technically that should not be too complicated to code such a configurator

generate the whole command would be quite much but it should be enough to generate the array code for the keyboard layout
