### ISSUE TITLE
Send Command from Html/Php page

### ISSUE THREAD

**Issue by farmaworld** [php-telegram-bot/core#1100]
how can I send a command from a page of a site. Let me explain better, I want to create html / php pages to send and / or receive info from a channel through my bot.
thanks

**Comment by noplanman** [comment]
This is actually very easy!

You just need to initialise the `Telegram` object and then you can use any `Request` method you like.

So the PHP that handles your form would have something like this:
```php
<?php

// You can do any data validation here.
$chat_id = $_POST['my_chat_id_input_field'];
$text    = $_POST['my_text_input_field'];

// Initialise the library with your API key.
new Longman\TelegramBot\Telegram($api_key);

// Send a message (or whatever else).
Longman\TelegramBot\Request::sendMessage(['chat_id' => $chat_id, 'text' => $text])
```

A better approach might be to initialise the library somewhere more general, so that other parts of your website have the ability to send messages too, if that's desired.

**Comment by farmaworld** [comment]
but if i have to send a message, files, photos etc to my channel, how do i recover $ chat_id?
Should I also initialize the message subject?
or for a channel it is always the same

**Comment by farmaworld** [comment]
my mistake $ chat_id = bot_username (@mychannel_name)

**Comment by noplanman** [comment]
@farmaworld So all good then?

**Comment by farmaworld** [comment]
yes thanks
