### ISSUE TITLE
step by step How to get rawdata or error log of our bot. 

### ISSUE THREAD

**Issue by hasbi204** [php-telegram-bot/core#1122]
**last_error_message":"Wrong response from the webhook: 500 Internal Server Error**
My bot is error and I want to check where the error is. please help me see or how to set error log updates

**Comment by noplanman** [comment]
The best place to look for errors is in your web server logs.

You can also [enable logging](https://github.com/php-telegram-bot/core/blob/1cf5d1fd38c81df7650358d1ae85a16957db5d22/doc/01-utils.md#logging) to output any errors to a file.

Alternatively, you can use the getUpdates method instead of the webhook and execute the bot directly from the command line, which will output any PHP errors that may occur.
