### ISSUE TITLE
Why not detecting super group messages on GenericmessageCommand?

### ISSUE THREAD

**Issue by aladaghlou** [php-telegram-bot/core#1177]
Hi.
I added my bot to group with admin access and when send types of message, not handled by GenericmessageCommand.php file !
Please help me.

**Comment by noplanman** [comment]
Do you have the [logging](https://github.com/php-telegram-bot/core/blob/2093cffa2a8e0497d12183178e17cadcc1d0f6d5/doc/01-utils.md#logging) enabled?

Please confirm that an update does get through to your bot, thanks.

**Comment by aladaghlou** [comment]
> Do you have the [logging](https://github.com/php-telegram-bot/core/blob/2093cffa2a8e0497d12183178e17cadcc1d0f6d5/doc/01-utils.md#logging) enabled?
> 
> Please confirm that an update does get through to your bot, thanks.

Hi.
No, logging is disabled :(  But when message edited in groups detected by Message/EditedmessageCommand.php file.

**Comment by noplanman** [comment]
Ok! Do you have multiple `GenericmessageCommand.php` files in your custom commands path?

If so, make sure you only have one, as they will conflict with each other.

**Comment by aladaghlou** [comment]
@noplanman 
I do used default structure by [example-bot](https://github.com/php-telegram-bot/example-bot) project and no creating custom command.
That mean has a bug or my configs has bug?

**Comment by noplanman** [comment]
@aladaghlou The example-bot repository is for examples only, not to be used directly as it is.

Inside the commands folder, there are different examples that show features of the library and how to use them.

In a proper project, you should only put the command files you really need, nothing more.
So it's possible that you have multiple commands with the same name (like `GenericmessageCommand`) in different files, which will cause problems.

Try starting with an empty commands folder and then only put the commands you really need in there, without any duplicates.

Hope that fixes the problem, otherwise we'll have to dig a bit deeper 😊

**Comment by aladaghlou** [comment]
@noplanman Thank you very much.Worked for me 😃👌 . I removed all GenericmessageCommand file and keep one. 

Thank you for your good guidance 🙏🌹
