### ISSUE TITLE
Send Text to many users

### ISSUE THREAD

**Issue by radian-rgc** [php-telegram-bot/core#1235]
Hello
Can i send message to the some of filtered users ? example, i have 100k users but i want to send message to 50k users.

I must sendMessage request for each user ? Is it possible for Telegram to identify this as spam?
Thanks

**Comment by allysa08** [comment]
yesSent from my Huawei Mobile-------- Original Message --------Subject: [php-telegram-bot/core] Send Text to many users (#1235)From: radian-rgc To: php-telegram-bot/core CC: Subscribed 
Hello
Can i send message to the some of filtered users ? example, i have 100k users but i want to send message to 50k users.
I must sendMessage request for each user ? Is it possible for Telegram to identify this as spam?
Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/php-telegram-bot/core/issues/1235",
"url": "https://github.com/php-telegram-bot/core/issues/1235",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by appoodeh** [comment]
Can I use sendToActiveChats to send a message to all users who only subscribed to a specific topic

**Comment by noplanman** [comment]
@appoodeh It depends what defines "subscribed to a specific topic".

The options for using `sendToActiveChats` are limited, so using a custom query will most probably be a nicer and safer solution.
