### ISSUE TITLE
Tutorial of creating bot with this package

### ISSUE THREAD

**Issue by Odilbukh** [php-telegram-bot/core#1270]
### 🎉 Feature Request
Tutorial of creating bot with this package. 
#### Summary
How to create new bot and features with this package? is there some tutorials ?

**Comment by noplanman** [comment]
Hi @Odilbukh 

You can take a look at the [example-bot](https://github.com/php-telegram-bot/example-bot/) repository for some examples of how to create custom commands.

As far as I know, nobody has made a "full" tutorial on how to use it. PHP knowledge is definitely required!

**Comment by Odilbukh** [comment]
Hi @noplanman  Thanks for answer!

I installed the package and webhook as written in README. My bot is working. BUT only admin commands works but another commands does not work even start command. Although I haven't changed it.

**Comment by Odilbukh** [comment]
ok! I fixed it

But how can I handle text that user send to bot.

Now in GenericmessageCommand files: 

$message = $this->getMessage();
        $user_id = $message->getFrom()->getId();
        $chat_id = $message->getChat()->getId();
        $text = $message->getText();
        $conversation = new Conversation($user_id, $chat_id, $this->getName());
        
        if($text !== null) {
            $text = $message->getText(true);
            if (stripos($text, 'tiktok')) {
                return $this->telegram->executeCommand('tiktok');
            }
            if (stripos($text, 'Menu') === 0) {
                return $this->telegram->executeCommand('menu');
            }

            if (stripos($text, 'Balance') === 0) {
                return $this->telegram->executeCommand('balance');
            }
            if (stripos($text, 'Send') === 0) {
                return $this->telegram->executeCommand('send');
            }
            return $this->replyToChat(
                'Command not found'
            );
        } 
        
        But nothing happens when user sends message to bot

**Comment by Odilbukh** [comment]
can you help me?

**Comment by noplanman** [comment]
Make sure there is only one `GenericmessageCommand.php` file in your custom commands folder, as multiple ones will override each other.

**Comment by devjet** [comment]
Hi @noplanman
Unfortunately example-bot isn't informative. (A way too OOP for simple feature examples)

Have a hard time to integrate with SLIM to create simple flow for inline and other features as menu.
(First, tried to integrate as Middleware, but result does not look cool)

At first look php-telegram-bot, looks pretty cool and powerful, 
but lack of simple examples (as on outdated [telegram-bot-php](https://github.com/formapro/telegram-bot-php) ) 
forcing me to look forward to another bot library, unfortunately. 
Sad about that a bit. 

Maybe this library require just documentation for method calls, and possibilities, otherwise need to invest in time to dig in source code. Isn't clear that it worth it, yet.
