### ISSUE TITLE
How can I get Message object from DB?

### ISSUE THREAD

**Issue by vgip** [php-telegram-bot/core#1328]
How can I get Message object from DB?

**Comment by TiiFuchs** [comment]
You can use the PDO object that is attached to the DB class.

```php
$statement = DB::getPdo()->prepare('SELECT * FROM ' . TB_MESSAGE . ' WHERE id = :id');
$statement->bindValue(':id', $messageId);
$statement->execute();

$message = $statement->fetch();
```

Please have a closer look on the PDO documentation: https://www.php.net/manual/de/pdo.prepared-statements.php
And of course, you need to know SQL to query the database.

I hope that puts you on the right track. But please understand that we are not able to help you any further since these are general PHP/Database things and are not special to this library.
