### ISSUE TITLE
Automatically remove user from the bot

### ISSUE THREAD

**Issue by bugbaal** [php-telegram-bot/core#1376]
Hi, is it possible to remove user to use the bot?

For example:
The user find the bot, press START button to join to the bot, but he isn't authorized to use the bot, so I want to remove he from the bot in the same way I do that manually from the app "Delete and Stop chat".

Thanks

**Comment by Hitmare** [comment]
Hi

What do you mean with "remove the User" ? the Bot works and functions quite differently then the User. While the User needs to give consent to the Bot by pressing the START button, the bot does not have such functions.

The Bot can always be talked to by everyone who has its Username. But you can implement your own whitelist so that the Bot will check with every message/command if it comes from a whitelisted (or blacklisted) user before sending a response

**Comment by bugbaal** [comment]
Yes, I took the blacklist method at the moment.
But I wanted to know if it was possible to kick off the user from the bot to avoid to process useless messages.
Also to avoid to save that messages in the DB

**Comment by Hitmare** [comment]
No. 
A User can block a Bot 
A Bot cannot block a User the same way. it only can just 'not respond' if a black/whitelist method is used
you can look up the Telegram Bot API and its function under https://core.telegram.org/bots/api

**Comment by bugbaal** [comment]
ok, thank you for the information
