### ISSUE TITLE
Append parameters to command, like "/edit_22456"

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#487]
I want to list some records for the user and add a quick link to do some action on any of them. Something like:
```
Subject: Hello
ID: 85
Remove link: /remove_85
```
which when the `/remove_85` is tapped, bot would remove that record having `ID=85`.
How to do it?

**Comment by noplanman** [comment]
Have a look at the [WhoisCommand](https://github.com/php-telegram-bot/core/blob/0.44.1/src/Commands/AdminCommands/WhoisCommand.php#L73) and the example [GenericCommand](https://github.com/php-telegram-bot/example-bot/blob/1a8fb293d47190a21592f7c3388c5d2101a374d6/Commands/GenericCommand.php#L51).

You should be able to see how they work, otherwise just ask again.

**Comment by ttvd94** [comment]
Thanks @noplanman that was exactly what I'm looking for.
`GenericCommand.php` was pretty clear.
But in the [WhoisCommand](https://github.com/php-telegram-bot/core/blob/0.44.1/src/Commands/AdminCommands/WhoisCommand.php#L77) on line 77, 78 and 79 there is a part of code that I couldn't find out what it is doing. Could you please explain it to me?

**Comment by jacklul** [comment]
Thats for group IDs, they are negative numbers so they are in format '-314234', and because the command line cant look like this: `'/whois-314234'` we replaced `-` with `g` and in the command we check if it exists on that string position and restore the `-` when needed!

**Comment by ttvd94** [comment]
Thank you @jacklul that was very helpful.
