### ISSUE TITLE
What is the difference between UserCommand and SystemCommand?

### ISSUE THREAD

**Issue by leoleoasd** [php-telegram-bot/core#530]
### Required Information
- Operating system:CentOS
- PHP version:7.0
- PHP Telegram Bot version:the newest
- Using MySQL database: yes / no yes
- MySQL version: 5.6
- Update Method: Webhook / getUpdates webhook
- Self-signed certificate: yes / no no
- RAW update (if available):

**Comment by noplanman** [comment]
SystemCommands are commands that get "executed" by Telegram and the Bot.
UserCommands are commands get executed by the user interacting with the Bot.

To get a better idea what this means, look at the different [System](https://github.com/php-telegram-bot/core/tree/0.44.1/src/Commands/SystemCommands) and [User](https://github.com/php-telegram-bot/example-bot/tree/master/Commands) commands for example.

Hope this answers the question, otherwise just ask again!

**Comment by wrewolf** [comment]
But copy HelpCommand from [User  ](https://github.com/php-telegram-bot/example-bot/tree/master/Commands)Command can't work, before move to SystemCommand....

**Comment by noplanman** [comment]
@wrewolf, the HelpCommand is a user command. It gets executed when a user sends `/help` to the bot. System commands cannot be executed by the user, instead they get executed when some event happens on the bot.

**Comment by wrewolf** [comment]
@noplanmanThe user sends `/ help` and there is no response
And inside the code if you dig and add your logs you can see that the error in finding the HelpCommand class in system commands ...
That's the way I guessed to move to this system (SystemCommand) and they began to respond to the sent commands by the user

**Comment by noplanman** [comment]
It searches for commands in this order: Admin, User, System.

Good catch @wrewolf! Users (or Admins) shouldn't be allowed to call system commands I think. They should be reserved for System only.

@jacklul What do you think? As it is at the moment, any user can just call System commands, which I'd just never done before!

**Comment by jacklul** [comment]
@noplanman I guess we could add another variable (just like with visible in help) that will disallow a command to be executed by user but only by the library itself. And leave everything else like it is - some people might consider commands like /cancel, /start a system command and keep them there rather than usercommand folder.

**Comment by wrewolf** [comment]
@noplanman my admin user cant's exec UserCommand, but AdminCommand i didn't try checks

**Comment by noplanman** [comment]
> my admin user cant's exec UserCommand

Really? If you have added custom commands folders that have both a UserCommand and an AdminCommand of the same command name, the Admin one should be called if you're an admin, else the User one.

Feel free to ping me on Telegram (@noplanman) so that I can dig into what's going on, which might be easier than posting lots of code and your project structure here.

**Comment by wrewolf** [comment]
One custom folder. And only one command file EchoCommand.php [ UserCommands namespace.]
not work
after change to SystemCommands work correct

**Comment by pooriamo** [comment]
> System commands cannot be executed by the user, instead they get executed when some event happens on the bot.

Except `/start`, right? @noplanman

**Comment by noplanman** [comment]
@pooriamo, the [`/start`](https://github.com/php-telegram-bot/core/blob/b6ea355a4d16e8b1879b6a485d664a6a5a9c6ea3/src/Commands/UserCommands/StartCommand.php) command is actually a `UserCommand` 😊

**Comment by pooriamo** [comment]
@noplanman So is [this](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/StartCommand.php#L29) wrong?

**Comment by noplanman** [comment]
@pooriamo That's still a left-over from how it used to be previously.

They both work, but it makes more sense as a bot developer to leave the system commands to internal operations.

**Comment by pooriamo** [comment]
@noplanman Yeah I guessed. But I was a little confused so I asked. Thanks, Armando.
