### ISSUE TITLE
execute command in callbackquery command

### ISSUE THREAD

**Issue by mohsenshahab** [php-telegram-bot/core#532]
### Required Information

- Operating system:
- PHP version: 7.0
- PHP Telegram Bot version: 0.44.1
- Using MySQL database: yes 
- MySQL version: 5
- Update Method: Webhook 
- Self-signed certificate: no
- RAW update (if available):

how can I execute a command in  callbackquerycommand

for example, I would like when pres a inlinekeyboard  . execute /start 
I used 
`   $this->getTelegram()->executeCommand('exec');` 
but this is  not working

**Comment by NabiKAZ** [comment]
I thinks it's useful: # 485

**Comment by noplanman** [comment]
@mohsenshahab Did you check the issue linked by @NabiKAZ?

Namely, this comment should work for you: https://github.com/php-telegram-bot/core/issues/485#issuecomment-298847941

**Comment by sadeghesfahani** [comment]
is these codes work for you? i can not call a command with inline keyboard!

**Comment by noplanman** [comment]
@sadeghesfahani Did you get it to work?
If still not, what error(s) do you get?

**Comment by sunildabhi** [comment]
i get bellow error:
PHP Fatal error:  Call to a member function isPrivateChat() on null in /vendor/longman/telegram-bot/src/Commands/Command.php on line 376

i used bellow code in CallbackqueryCommand.php  execute() method

`   $update = json_decode($this->update->toJson(), true);
    $update['message']['text'] = '/start';
    return (new StartCommand($this->telegram, new Update($update)))->preExecute();`

**Comment by noplanman** [comment]
Right, you need to adjust your `StartCommand` to get the correct message object, or you'll need to add some extra tweak to the code you're using now.

Try using this to get the `Message` object:
```php
$message = $this->getMessage() ?: $this->getCallbackQuery()->getMessage();
```

Does that fix it?

**Comment by sunildabhi** [comment]
i changed StartCommand::execute() in StartCommand.php
`$message = $this->getMessage() ? $this->getMessage() : $this->getCallbackQuery()->getMessage();
        $chat_id = $message->getChat()->getId();`

but still same error

**Comment by noplanman** [comment]
Can you share your `StartCommand.php` and `CallbackqueryCommand.php`?

Alternatively, you can also get in touch with me via Telegram directly if you prefer not to share your code publicly: [@noplanman](https://t.me/noplanman)

**Comment by akalongman** [comment]
Is this still actual?

**Comment by noplanman** [comment]
This has to do with the fact that the [`raw_data`](https://github.com/php-telegram-bot/core/blob/7701428356a70b0b5d88404248a060ca1c43c6ba/src/Entities/ServerResponse.php#L158) isn't being set for result objects.

So when trying to get the JSON of the Update object, `null` is returned, as there is no `raw_data` property in the Update object. This then causes a problem when using that returned value (which is now `null`) to instantiate a new Update object, which fails because an `array` is expected and `null` is passed.

Example where it fails (in `CallbackqueryCommand.php::execute()`):
```php
$update = json_decode($this->update->toJson(), true);
return (new MyCommand($this->telegram, new Update($update)))->preExecute();
```

In these simple cases, the Update object can just be passed directly:
```php
return (new MyCommand($this->telegram, $this->update))->preExecute();
```

The whole raw data passing is a bit messy and could do with clearing up :confused:
