### ISSUE TITLE
/stats  command

### ISSUE THREAD

**Issue by MBoretto** [php-telegram-bot/core#64]
Hi guys,
it would be great to develop the _/stats_ admin command!  
This command should use as input the messages collected in the DB and then show the number of request per day to the bot. 
Is someone interested? Some volunters in the develop of this feature? ;)

**Comment by Excody** [comment]
Hi, I have an outline of the team that bypassing the main DB class accomplishes this . In the coming days I'm going to add this functionality to a class of DB, and can be published as soon as it is completed yet .

**Comment by MBoretto** [comment]
Very good!

**Comment by skmohammadi** [comment]
Hi. What is mean of `['text' => 'callback', 'callback_data' => 'identifier']`? what is identifier? where it is defined? Why when i press the this button, bot show popup that say "Hello world!".

Please describe.

**Comment by jacklul** [comment]
Because you're using example commands. You should go through all of them and read the code and understand it. 
Then start creating own commands, you can literally copy all SystemCommands to your project dir and set `    $telegram->addCommandsPath($commands_path);` pointing to it, thats where you can start developing your bot commands!

**Comment by antimech** [comment]
@skmohammadi 
> src/Commands/SystemCommands/CallbackqueryCommand.php

**Comment by skmohammadi** [comment]
yes, i found that. thank you @antimech

**Comment by noplanman** [comment]
I'll close this for now, as this would be included in some analytics feature, if that becomes a thing at some point.
