### ISSUE TITLE
Duplicate update received

### ISSUE THREAD

**Issue by jagdtiger9** [php-telegram-bot/core#659]
After a month delay **getUpdates** recieves "update's unique identifier" less than previous ones.
![_039](https://user-images.githubusercontent.com/24798160/30908155-7009630c-a385-11e7-992a-3b8ab03500bf.png)

So that code doesn't work OK, error "Duplicate update received" occures.
./telegram-bot/src/Telegram.php
line:338
$last_update = DB::selectTelegramUpdate(1);

**Comment by kruteev** [comment]
similarity. there are solutions?

**Comment by sergeolkhovik** [comment]
Confirming.
My code doesn't use web hooks:
            $tg->enableMySQL($dbc, 'telegram_');
            $tg->addCommandsPath(ROOT . DS . 'telegram');
            $tg->enableLimiter();
            try {
                // $tg->runCommands(['/help', '/password']);
                $tg->handleGetUpdates();
            } catch (TelegramUnauthorizedException $e) {

From time to time, any message from user to bot generates this error.
Have to clean telegram_update and message tables manually.

**Comment by aerdnar** [comment]
This bug is still here! In https://github.com/php-telegram-bot/core/blob/0.61.0/src/DB.php#L192 they order by update_id but this number is not always in sequence. 
Telegram explain this https://core.telegram.org/bots/api#getting-updates :
- Incoming updates are stored on the server until the bot receives them either way, but **they will not be kept longer than 24 hours**.
- update_id: If there are no new updates for at least a week, then identifier of the **next update will be chosen randomly instead of sequentially**.

The query in DB::selectTelegramUpdate() should ignore older update_id more than 48 hours.
This can be fixed by query where date/created_at values are acceptable.
