### ISSUE TITLE
Best safe way to add columns to database?

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#769]
What is the safest way to add more columns to any table of the database? In my case, _user_ table.

**Comment by jacklul** [comment]
Just add them normally with `APPEND TABLE ...`, nothing will break since we are using prepare statements with chosen list of columns.

I have for example modified `user_chat` table to have field `active` which is set to `true` if user is in that group chat and `false` if he's not (bot tracks newchatmembers and leftchatmember updates and updates data in that table).

**Comment by ttvd94** [comment]
Great! thanks @jacklul
