### ISSUE TITLE
Get all "*Command.php" files and return null

### ISSUE THREAD

**Issue by zhangziliangs** [php-telegram-bot/core#891]
use webhook and commands

php 7.1.9
core:0.53
```php
//Get all "*Command.php" files
$files = new RegexIterator(
    new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path)
    ),
    '/^.+Command.php$/'
);
```
I has many command.php like `TestCommand.php` `StartCommand.php` and so on.
return `null` why???

**Comment by noplanman** [comment]
Hi @zhangziliangs 
This is a general PHP question.

What you get returned is an instance of `RegexIterator`, not an array of files.
You can get the items of the iterator as an array like this:
```php
/** @var \SplFileInfo[] $files */
$files = iterator_to_array($files_iterator);
```

Or loop the iterator to get all the files like this:
```php
/** @var \SplFileInfo $file */
foreach ($files_iterator as $file) {
    // $filename  = $file->getFilename();
    // $full_path = $file->getPathname();
    // etc.
}
```

Also, you'll want your regex to be like this:
`'/^.+Command\.php$/'`
(notice the backslash at`\.php`, otherwise the `.` will interpret any character :wink:)
