### ISSUE TITLE
sendToActiveChats('sendPhoto') only works once per call

### ISSUE THREAD

**Issue by 0xEAB** [php-telegram-bot/core#900]
### Required Information

- Operating system: Linux
- PHP version: 7.1.22 (64bit)
- PHP Telegram Bot version: **0.54.1**
- Using MySQL database: yes
- Self-signed certificate: no

### Expected behaviour
Photo should be sent to all active chats.

### Actual behaviour
Photo seems to be sent to the first chat only.
This is the response I'm getting for the rest of the chats:
```php
object(Longman\TelegramBot\Entities\ServerResponse)#192 (5) {
    ["ok"]=>
    bool(false)
    ["error_code"]=>
    int(400)
    ["description"]=>
    string(45) "Bad Request: there is no photo in the request"
```

### Steps to reproduce
```php
Request::sendToActiveChats(
    'sendPhoto',
    ['photo' => Longman\TelegramBot\Request::encodeFile($row['path'])],
    [true, true, true, null, null]
);
```

### Extra details

I'd guess `sendToActiveChats` doesn't reset the stream to offset 0 (but I haven't looked into it yet).
This might also apply when `sendToActiveChats` is used with `sendDocument` and similar methods.

**Comment by noplanman** [comment]
@0xEAB Thanks for reporting, was able find the cause.

You're on the right track. Guzzle internally converts resources into streams, making the existing one invalid after being posted once.

As a temporary fix, you can use this:
```php
['photo' => \GuzzleHttp\Psr7\stream_for(Longman\TelegramBot\Request::encodeFile($row['path']))],
```

I'm not sure yet if changing this directly in the `encodeFile` method will break anything, as it will then return a `Stream` instead of just a simple `resource`. This could potentially break existing user code, if they rely on the returned resource :confused: 

@php-telegram-bot/developers What is your view on this?

**Comment by noplanman** [comment]
@0xEAB If you update to version 0.56.0 you can now simply pass the path as a string (which will internally automatically use a stream):
```php
Request::sendToActiveChats(
    'sendPhoto',
    ['photo' => $row['path']],
    [true, true, true, null, null]
);
```
